# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
      - dev
  pull_request:
    branches: [ main,dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install prerequisities 
        run: | 
          sudo apt-get install -y curl build-essential python3-pip python-pip
          pip install pyserial

      - name: Install Arduino CLI 
        run: cd ~ && sudo curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
      
      - name: Add Arduino CLI to PATH 
        run: |
          export PATH="/home/runner/bin:$PATH"
          source ~/.bashrc
          echo $PATH
          
      - name: Update Arduino CLI indexes
        run: /home/runner/bin/arduino-cli core update-index --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

      - name: Install ESP32 SDK
        run: ./arduino-cli core install esp32:esp32 --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
 
      - name: Run CI on sketches
        run: |
          ./arduino-cli compile --fqbn esp32:esp32:featheresp32 sketch1/sketch1.ino
          ./arduino-cli compile --fqbn esp32:esp32:featheresp32 sketch1/sketch1.ino

